name = "WangLandau"
uuid = "8fe66260-677e-4fa0-b9cd-b744032f5639"
authors = ["Chris Bradly"]
version = "0.1.0-DEV"

[deps]
CommonSolve = "38540f10-b2f7-11e9-35d8-d573e4eb0ff2"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
CommonSolve = "0.2.4"
Random = "1.11.0"
StaticArrays = "1.9.10"
TOML = "1.0.3"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
