name = "WangLandau"
uuid = "8fe66260-677e-4fa0-b9cd-b744032f5639"
authors = ["Chris Bradly"]
version = "0.1.0-DEV"

[deps]
CommonSolve = "38540f10-b2f7-11e9-35d8-d573e4eb0ff2"
ProgressLogging = "33c8b6b6-d38a-422a-b730-caa89a2f386c"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
TerminalLoggers = "5d786b92-1e48-4d6f-9151-6b4477ca9bed"

[compat]
CommonSolve = "0.2.4"
ProgressLogging = "0.1.4"
Random = "1.11.0"
StaticArrays = "1.9.10"
TOML = "1.0.3"
TerminalLoggers = "0.1.7"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
